export const majorCities = [
  "Ahmedabad",
  "Bangalore",
  "Bhopal",
  "Bhubaneswar",
  "Chandigarh",
  "Chennai",
  "Coimbatore",
  "Delhi",
  "Gurugram",
  "Guwahati",
  "Hyderabad",
  "Indore",
  "Jaipur",
  "Kochi",
  "Kolkata",
  "Lucknow",
  "Mumbai",
  "Nagpur",
  "Noida",
  "Patna",
  "Pune",
  "Surat",
  "Thane",
  "Vadodara",
  "Visakhapatnam",
];

export const cityFilterOptions = ["All", ...majorCities];
